DROP TABLE IF EXISTS book_boxes CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS library_sections CASCADE;
DROP TABLE IF EXISTS borrow_records CASCADE;
DROP TABLE IF EXISTS users CASCADE;